apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  ports:
  - port: 8080
    protocol: TCP
  #type: NodePort
  selector:
    app: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}
      restartPolicy: Always
---
#Ingress jenkins
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
  annotations:
    nginx.org/client-max-body-size: "10m"
    #Jika ingin memaksa memakai HTTPS
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: jenkins.gonnabegood.xyz
    http:
      paths:
      #- path: /
      - backend:
          serviceName: jenkins-service
          servicePort: 8080